/*
 * generated by Xtext 2.11.0
 */
package org.bynar.versailles.xtext.ide


/**
 * Use this class to register ide components.
 */
class VersaillesLangIdeModule extends AbstractVersaillesLangIdeModule {
}
