/*
 * generated by Xtext 2.12.0
 */
package org.bynar.xtext.formatting2

import com.google.inject.Inject
import org.bynar.versailles.xtext.formatting2.VersaillesLangFormatter
import org.bynar.xtext.bynarLang.RecordAlign
import org.bynar.xtext.bynarLang.RegisterComponent
import org.bynar.xtext.services.BynarLangGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class BynarLangFormatter extends VersaillesLangFormatter {
}
