/*
 * generated by Xtext 2.10.0
 */
package org.bynar.versailles.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VersaillesLangStandaloneSetup extends VersaillesLangStandaloneSetupGenerated {

	def static void doSetup() {
		new VersaillesLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
