/*
 * generated by Xtext 2.10.0
 */
package org.bynar.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BynarLangStandaloneSetup extends BynarLangStandaloneSetupGenerated {

	def static void doSetup() {
		new BynarLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
