/*
 * generated by Xtext 2.10.0
 */
package org.bynar.xtext.tests

import com.google.inject.Inject
import org.bynar.versailles.xtext.versaillesLang.CompilationUnit
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BynarLangInjectorProvider)
class BynarLangParsingTest{

	@Inject
	ParseHelper<CompilationUnit> parseHelper

	@org.junit.Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
